/* Automatically generated by configure - do not modify */
#define ARCH_X86 1
#define TUNECPU generic
#define HAVE_MMX 1
#define __CPU__ 586
#define HAVE_BUILTIN_VECTOR 1
#define HAVE_LRINTF 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_ZLIB 1
#define CONFIG_WIN32 1
#define HAVE_W32THREADS 1
#ifndef __MINGW32__
#define __MINGW32__ 1
#endif
#define HAVE_MALLOC_H 1
#undef  HAVE_MEMALIGN
#define MEMALIGN_HACK 1
#define SIMPLE_IDCT 1
#define CONFIG_RISKY 1
#define restrict __restrict__
